agents:
  PDM4ARSpaceship: # do not change this name
    state:
      x: -8.0
      y: -8.0
      psi: 0.26179938779 
      vx: 0.0
      vy: 0.0
      dpsi: 0.0
      delta: 0.0
      m: 2.5
    goal:
      type: static
      state: 
        x: 8.0
        y: 8.0
        psi: 0.0
        vx: 0.0
        vy: 0.0
        dpsi: 0.0
      pos_tolerance: 0.5
      dir_tolerance: 0.5
      vel_tolerance: 1.0
    color: 'blue'

planets:
  Namek:
    center: [0.0, 0.0]
    radius: 3.0
    satellites:
      Cereal:
        tau: 0.0
        orbit_r: 6.0
        omega: 0.25358
        radius: 0.45
      Beehay:
        tau: 3.14159
        orbit_r: 7.0
        omega: 0.17248
        radius: 0.45
      Anoyo:
        tau: 1.5708
        orbit_r: 8.0
        omega: 0.12353
        radius: 0.45
      Zun:
        tau: 4.71239
        orbit_r: 9.5
        omega: 0.09202
        radius: 0.95

boundary:
  corners:
    - [-11, -11]
    - [-11, 11]
    - [11, 11]
    - [11, -11]
    - [-11, -11]

seed: 98