# Test case 1 in pdm4ar_scvxx
agents:
  PDM4ARocket: # do not change this name
    color: 'blue'
    state:
      x: -8.0
      y: -8.0
      psi: 3.141592653589793
      vx: 0.0
      vy: 0.0
      dpsi: 0.0
      phi: 0.0
      m: 2.1
    goal:
      type: static
      state: 
        x: 8.0
        y: 8.0
        psi: 0.0
        vx: 0.0
        vy: 0.0
        dpsi: 0.0
      pos_tolerance: 0.5
      vel_tolerance: 0.5
    

planets:
  Namek:
    center: [5.0, 4.0]
    radius: 3.0
    satellites: {}
  Yardrat:
    center: [-5.0, -4.0]
    radius: 3.0
    satellites: {}
  Vampa:
    center: [0.0, 0.0]
    radius: 2.0
    satellites: {}

boundary:
  corners:
    - [-10.0, -10.0]
    - [-10.0, 10.0]
    - [10.0, 10.0]
    - [10.0, -10.0]
    - [-10.0, -10.0]

seed: 98
