agents:
  PDM4ARocket: # do not change this name
    state:
      x: -8.0
      y: -8.0
      psi: 3.141592653589793
      m: 2.1
      vx: 0.0
      vy: 0.0
      dpsi: 0.0
      phi: 0.0
    goal:
      type: satellite
      name: Vegeta/Kelbo
      pos_tolerance: 0.7
      vel_tolerance: 0.7
    color: 'blue'

planets:
  Vegeta:
    center: [0.0, 0.0]
    radius: 3.0
    satellites:
      Kelbo:
        tau: 5.2359
        orbit_r: 7.0
        omega: 0.05454
        radius: 0.5

boundary:
  corners:
    - [-11, -11]
    - [-11, 11]
    - [11, 11]
    - [11, -11]
    - [-11, -11]

seed: 98