agents:
  PDM4AR_1:
    state:
      x: -20
      y: -40
      psi: 1
      vx: 2
      delta: 0.02
    goal: 16
    color: 'red'

static_obstacles:
  centers:
    - [-5, 10]
    - [-30, -20]
    - [-10, -15]
    - [-22, 0]
    - [10, 60]
    - [20, 45]
  avg_radius: 2
  irregularity: 0.3
  spikiness: 0.5
  n_vertices: 10
