task_level: 3

testcases:
  -
    scenario: "USA_US101-15_2_T-1"
    max_sim_time: 15.0
    ego:
      original_name: P20
      goal_lane_id: 28
    others:
      names: [P5, P8, P9, P10, P16, P17, P18, P24, P26, P28, P29, P30, P31, P32, P33, P34, P35]
    description: "scenario1"

seed: 98