agents:
  PDM4AR_1:
    state:
      x: -9.360260414954451
      y: 2.967390075775155
      psi: -1.3439048784363092
    color: saddlebrown
  PDM4AR_2:
    state:
      x: -1.5251068413680393
      y: -1.401735529530372
      psi: 3.1107935149598713
    color: steelblue
  PDM4AR_3:
    state:
      x: 2.3199999404150393
      y: -1.3142018173186614
      psi: 0.8763115224888205
    color: firebrick
static_obstacles:
- - - 1.2703945759730217
    - 2.5092471896670387
  - - 0.42232047435354847
    - 4.35141898466595
  - - 5.057014795676071
    - 3.89871357922184
  - - 4.672368868728196
    - 1.3959347516368332
  - - 2.368166787708724
    - 1.6388533692864908
  - - 1.2703945759730217
    - 2.5092471896670387
- - - -3.0638083167079615
    - -5.30875473629813
  - - -3.928575136586758
    - -5.6099641293660625
  - - -4.150388730901414
    - -3.9083359374799227
  - - -3.0338534612001
    - -4.375652121143782
  - - -3.0638083167079615
    - -5.30875473629813
- - - -1.0647246947812645
    - 0.06971074758039694
  - - -1.7643086863881194
    - 0.8943651355487807
  - - -1.6166674985260574
    - 1.5090691401281715
  - - 0.21336535491733266
    - 0.16086366734442348
  - - 0.13022206022766314
    - -0.1692931777975955
  - - -1.0647246947812645
    - 0.06971074758039694
- - - 2.173635554643087
    - -5.1749456000336505
  - - 1.5470188547392543
    - -4.829653628064744
  - - 4.143210312053391
    - -2.697219782417079
  - - 4.631821256011589
    - -3.317254659030967
  - - 2.173635554643087
    - -5.1749456000336505
- - - -4.169646037832709
    - 6.3820674947947
  - - -5.143346138222477
    - 5.704783634825574
  - - -5.724604231664128
    - 6.029556966299614
  - - -5.993169409469835
    - 6.987412447937291
  - - -5.143819877165526
    - 7.662262806717004
  - - -4.169646037832709
    - 6.3820674947947
- - - 4.639757421397757
    - 6.9571669556562865
  - - 5.785256550684215
    - 7.815500825346079
  - - 7.366303116187623
    - 7.665241146868273
  - - 4.784231990317926
    - 6.905494439742991
  - - 4.639757421397757
    - 6.9571669556562865
- - - -6.208060782460139
    - 2.7156686446245857
  - - -6.786589636716313
    - 1.7710476709675351
  - - -7.60923878423815
    - 1.9315794270721955
  - - -8.461139880452786
    - 2.534230096925455
  - - -6.208060782460139
    - 2.7156686446245857
- - - -7.687454478566753
    - -4.015410328475795
  - - -7.045993024042204
    - -4.355959679427574
  - - -8.062866997318359
    - -5.851991348532653
  - - -7.687454478566753
    - -4.015410328475795
- - - 7.031769221674441
    - -4.818271455511712
  - - 5.5972453667011335
    - -6.954256691317887
  - - 5.530744283205465
    - -6.5291607756630095
  - - 7.031769221674441
    - -4.818271455511712
- - - 7.773255106962495
    - -0.052838900490264074
  - - 8.333031348103708
    - 0.149323770004413
  - - 8.73844226157447
    - -0.26592391026627116
  - - 7.106068886207649
    - -0.6459076638405445
  - - 7.773255106962495
    - -0.052838900490264074
boundary:
- - -11.0
  - -11.0
- - -11.0
  - 11.0
- - 11.0
  - 11.0
- - 11.0
  - -11.0
- - -11.0
  - -11.0
seed: 42
shared_goals:
- id: goal_1
  center:
  - -2.8848056233297372
  - 1.3850088340396045
  radius: 0.3
- id: goal_2
  center:
  - 0.4602973304929421
  - -2.732166348945241
  radius: 0.3
- id: goal_3
  center:
  - 5.613681782568225
  - 0.14940274105502915
  radius: 0.3
- id: goal_4
  center:
  - -9.401447596751952
  - 7.317296195139345
  radius: 0.3
- id: goal_5
  center:
  - -8.946725266731178
  - -2.217126098063792
  radius: 0.3
- id: goal_6
  center:
  - 2.798794077573321
  - 6.475519672566612
  radius: 0.3
- id: goal_7
  center:
  - 3.6197783016160763
  - 9.424056041461448
  radius: 0.3
- id: goal_8
  center:
  - -0.4207890362886886
  - -6.227351231088084
  radius: 0.3
- id: goal_9
  center:
  - -7.156889408552868
  - 4.234483128885415
  radius: 0.3
- id: goal_10
  center:
  - 8.694660953957733
  - -9.075117712084397
  radius: 0.3
- id: goal_11
  center:
  - 7.561491558114859
  - -3.614321927025384
  radius: 0.3
- id: goal_12
  center:
  - -3.7225126944369205
  - -1.9948085085540663
  radius: 0.3
collection_points:
- id: collection_1
  center:
  - -1.4274614835673916
  - 5.136810967018375
  radius: 0.8
- id: collection_2
  center:
  - -4.879891784478635
  - -7.033620780049715
  radius: 0.8
- id: collection_3
  center:
  - 2.2842765711420263
  - -8.131786991194213
  radius: 0.8
config_name: config_3
